import type { Metadata } from 'next'

import '@/styles/sass/globals.scss'
import { LocationProvider } from '@/utils/Context/Location'
import { Provider } from '@/utils/Context/Query'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <LocationProvider>
          <Provider>{children}</Provider>
        </LocationProvider>
      </body>
    </html>
  )
}
